
jwt:
  access_token_secret: PHnERYoF051vtpoFUmjyQ8i2d/8sSSyXQ6+6tl4HtXs=--/nAvZM5n7/Vk2OEwlGxZxA==
  refresh_token_secret: QQQY+kvzhf2zR4Iu9krijQlksIQIfPinl0Ye3r5sSPk=--h8eeQZKLEYQllefX4/WZjg==

swagger:
  username: +mdSN/swWZueVhynDvo90dYCZwobKCtxHchXt8wHJT0=--l/Cw+dicEwuhw6PkHXUiFQ==
  password: ZgEvvmgj1Od6ImwCVMDYJvkl5HXkxz7xNAhA3LnSWAw=--J90p5f+LfWDCyvlmsERVjg==

database:
  name: D3jO1ciuPx9sMDJCVaQ7QsfaVzmwc3ji6fjmc75en1Q=--XTKqTqMG+6b3VqfhHpvbNw==
  host: jfglEznLfjEQxHFc+1rULg==--KSwh2EMjOs+HXiAPef03kA==
  username: iuqG2YxVyT8AmcrG5TVfNw==--/IrSaKOhLmShAgS2KPF24w==
  password: kJiaTpN6RQwigvQ97ERT2Q==--b5SunsuA0Vl0VBhuHl22Hg==
  port: NEulLRbxViGvMPmS93OgTA==--r3gf23MgOBxrkdqUQjJeqg==

emailLogin:
  tables: l9tbQlZ+2KB5DvsAwc09TQ==--c0X71Z3WB3PXOX+oaDQDxA==
  passwordMinLength: 0m1TAMJ7y1vnOAtNus0fWw==--8q4JFnq06RAcD8g4c0DKbQ==
  rememberFor: LGhcCsAIpP+wU9lPKv/5hQ==--rcwjbhzwGGVUSxHc6f4ZyQ==
  resetPasswordWithin: hgrR2HGGh1jwUyeuaccbGA==--gR9Q/GsHsaOewg25S0CwpA==
  maximumRetries: 2mOMFyNGMUfkioIxuitJag==--brzRGdd5478ZIbRJSxAwLw==
  unlockIn: krZNd/SvQ/jfNuyqN73WPw==--pOmlUVFquHQUXKq4B/qjWQ==
  passwordRegex: J5cvhTHplMVnPBuMq6aJZftYu3a2u4D92M1my9SL0ncuZsrsVO97HF06+h4Npmnw3/lYtF0tP5oI5t2U0tmeIObdUm/8f9Tg/s9Ar2y71RY=--fBvVGktP1lsyyyF07aK+dQ==


