
jwt:
  access_token_secret: ZyiW6Dz1/Uty6vzqgbKnV5dmCD2qeW2025MWYUzcrrE=--powmqGE6uvEvu9bwMAomBA==
  refresh_token_secret: 9DITV5Di7/CoHNmNlk0yKGh3IDllU5GFKR0+HOKNiGk=--2P1vczWzoobbWlmd0qeYUw==

swagger:
  username: oOwjs5mOztSfWZLQ+9Ubh7SNKAci+WKMVqmoNB9l2ec=--RyTinrH/BmhXZBLFP6/LzQ==
  password: LInRN4Qc7Wd/IfbUUDdsqZf4RIb5cjD8oDLprUlEu00=--+BRH19Cfep6AG0T1bxn9Bg==

database:
  name: IS+HEVypnRjR8Ra7CUfezo/Yc3fDNYHGvDUxiRyZFG4=--O/O9FqRaSAMNRWt9TrhWTA==
  host: 54en0y6vk1YWQO65LEplPg==--I+502Yts9ad66cV/GRaqdQ==
  username: hgc78NxeXS+KzYtmXcF7kg==--m+xOPXGdLtRal96Dq9b1GQ==
  password: jxdNz49ZJVJjg32n3r5D3A==--1U/t31V3e3JQmRxOzSagAA==
  port: Oqu5yTMkJYiTkVSiBiG+dA==--Ut5TAi669UtUoTHBtD0+jA==

emailLogin:
  tables: rfRuF5hKxESsquXC5xGKcg==--lAmuKjlVXT5N+VeVKduvdQ==
  passwordMinLength: plEoXoeM5RnzxeDmX9UVZg==--m/DNvMArmEM+zL+q8KgnPQ==
  rememberFor: 88U8JkSRBx3tMP1bkalllA==--/1a8dwSsazX+wQChpSf6AQ==
  resetPasswordWithin: iEk/Vq/0FnZ0Fx1FQJbpAQ==--XjNYbj/E0hdnZr9ps1scrQ==
  maximumRetries: 05iQMYjiCNXqoXvuZoYzjQ==--lJIIxIbp1LOKNJbEbm39ew==
  unlockIn: bxJObted3KYjIPfFQ0X5ZA==--3RcbKMiq8xuBIu1TTAXzBQ==
  passwordRegex: I0+HXAPkY7iFi/Q5nV5hIfedQPdFpcmkvMmOZ31+uJ6BHw9E/3qx+bn/5++Rf6/36BUNR6C+4R0vs9NGnt4pdEPjZ9IkvHB66aJSnU9v6ao=--Ptpg8ETXnodkuNUfiabyww==


