
jwt:
  access_token_secret: rhRA1OyxeEgz4WZoFBwhmUGVWVTwhENoqmNu1KTlLhg=--a1qzjj5JcKJMIk8bLuhExQ==
  refresh_token_secret: 3qIi1QF4Z252vq2fZ6aVk6g0jCQN9R75aMdsh0Kq53A=--SsFD3JMDzs91E1phXcJ6Ng==

swagger:
  username: jD8hgEbTbypgyl9czIsMzvLqV8btJEuqRMSZlvRasqQ=--c+h5ulrozidHluaSIJ8jTA==
  password: Bvqd/c6TCDb+ulNX+kmewMiTVM1FYeDQ179+nPRHap8=--coGECTTPQ7aZV5JX/GsdRg==

database:
  name: JftFXWrRswnTgF+BXePbCDY23VSMjVsxkriJZFyZ/o4=--4Iiv+4jSnIWaSwl8fQZpYQ==
  host: ess5hClfdALxMTZCbnaeYg==--4iDv8VaEtxTc8VlIOTOc+Q==
  username: 1SlZbj61+CSielZaSEAjVA==--n5MSmL68l525IMjaaI5hSw==
  password: T5jP2pFjigC/0FSN1bFWpA==--YsNlV1fS8dndLUecQkyDSw==
  port: MvzXfdDXIM04oTpoXpHWAQ==--g3aOLm5DqPpU/l4gDl2gwg==

emailLogin:
  tables: tfDPSf9NeNV16cD7n+2rJg==--+tmaUQe0qF+qrEDLObRrEQ==
  passwordMinLength: nzCV64Y62zv0eheMKg3fXg==--FAHwN2puKcQUzMnIczWbew==
  rememberFor: R5Ww3JYc0zVo3Df9e6znBQ==--Rk/nWdPzbOmi2Q5nBkFPLg==
  resetPasswordWithin: IdS6OWjfqY3uZ6klOd/G2w==--6JqdAZIJPPA9byWQ0RZYQA==
  maximumRetries: fk1IlisfRCrdifMxUNvqdg==--UFXBXJ5L/MLxyF13uIpgaw==
  unlockIn: Q6xYk8oiZ4fVyS6aYZQ51w==--bOiUbpXyfr50sVus99myIw==
  passwordRegex: 7Y1emudz5DlQtjDJ7AtjbaSVgXZ8MohPgkXu6zElwL4gpU37zctEVuusgfMP9lBbylo8XaqzF8oAyKtcKbCL1ik2UCBnTV6L4gyQ8EKxYm0=--B6EnQHUHMZKqGAKcAQcFwg==


