
jwt:
  access_token_secret: FoB5qUeMBITa4vjY7RfnUxscma58a4IoK8AmKIfnOR0=--lpt6ZxYLWUhbb44DJ4EViw==
  refresh_token_secret: tBeuW5ATuilwJ5RdFAT/1AYhINvWpffOUMYsK5MMteI=--cm/9IqsRwHprCSGWBNnQpw==

swagger:
  username: KzGa9vN37ilk4ku9xPazj4q3Do003pCeZGMvcDgKtWk=--ZwQiXHU+QY/nbCR7vIKyIw==
  password: pIZVRUNi6IcyHvjDK9rCFURKg7Iuy8xrP9bhPHE2U48=--rfaQxuF4SQKnkJ8e6wKiSQ==

database:
  name: Yv43YDM/U9G8Mdd7WILkNnjc7PSWt4vScSQ0QlJu5Ts=--9qBtfml7Yfh5hRVoyupnFw==
  host: DGy1X6JZCirYuRHWUcTX4Q==--Ick5pZTee/Fpa1Ulv6KK/A==
  username: gIC+94O7KshLn01T0McJng==--G/Q2AZQUivEdHsOmaEWvzA==
  password: ggPpBNFj9zdEk4oNcjAu0A==--O/hk1lKVPcWSABrU6oAlfw==
  port: KoRMYF6j92H46U+gtvbCZg==--gQds9dJrKNiTeyFFSmCHmQ==

emailLogin:
  tables: twmTZLhFTQ83PrZklMr6ZA==--RfbCU4YPvmjfdzSFVFuOTw==
  passwordMinLength: wM7wWDrVJYXrRVLbaxoNmA==--PF0oeifnujkmcS44ojsTPQ==
  rememberFor: 1miqLiUj847AL5yEYdv5/g==--tGjag3/klG/ZFQgIXDipIQ==
  resetPasswordWithin: IxfgL1+42iT6PB8S60rzGw==--7rbPDtzHL4bHSOnGq7zXUA==
  maximumRetries: 8zVTmqPZW/aviHaeKTGRBw==--5qO7NtRRlIDrYcepxy9MYw==
  unlockIn: UV272HfK0haQKBVYcVeauw==--re+EYERGty9x7cCBFcp8pQ==
  passwordRegex: fCae/OkKQjyCyYu9rFH0MEVfVmzyl7dXjiAX6c/1ktRRm/A9BvdpQ0XZ62CtM+c4+jSJKqkZ9Bjxy7gERqUfR4MbSC4wraG5ZV+XfGr2qmU=--ZN18WKJ8IYwslM5jExsccQ==


